version: '3'
services:
  app:
    container_name: classguardian_server
    build: .
    ports:
      - 3000:3000
    restart: always
    environment:
      DATABASE_URL: "postgres://postgres:password@db:5432/classguardian?schema=public"
      JWT_EXPIRATION: "24h"
      PRIVATE_KEY: "-----BEGIN RSA PRIVATE KEY-----\nMIIEowIBAAKCAQEA3UqFbfl58DjvnWLVWTxE+THLXzzddeWD6bFnFdChnZv2sKo5\n3XVv6DwMZonTKglltxgdUwXuPrvLnVuaV3i4qP8WscpQcieC2AP10ZYA1701tNFX\nFGlxDypaeZhqcXklet5aZ3uMvV/YhVl5SJrCY6k5r02X6lPE5/YgzwZjCOUJPGUQ\nGRwb1W4vnguWBFCttriQSdDXy0q+wAdUYMB6EjV0ZCC8bej4P/iz8mtBwB9ULAr6\nIAIiVZq1O4jNPbDJribfL3ZbQGuZQV7JrAa+1Op3XEtr9Nu4kz71nPloFfMC4YnW\nSViXVR4koDgJkSlHlrpP+WcXT9uT25DcgNSbYQIDAQABAoIBAQCLDRGs2i+6ODyw\n+/KuAQYiRBzT+m36cD8ksHnjJlb3r5IizsRPmUS5fEoagI51ArSsiXWbvsVHHEBE\n39OrFUuLvcan70X/hT5duJdVnFlpNxaxST3bsKn/apCxiYmRRhu8Ck5qaiM0uC5Z\nFLD2Y3C0qRh7RFmqP/sh+vIAxLWkVwOSF7DjQjNW9rzt7md8sTQuN+ylr6+CAKE5\nFzvZD7jVgMG02wlFteHpAEmkjXGkYoG+tGNuMDqI69Gv/j3Gy7oz6Zj8KFOUvECi\nJ8+8APkajWE9liF0mWw6xP/a5v4NSAQMdvbuJkVUw41VGymsAf1espp0qlF1IC4Y\ntTMD6DV1AoGBAPudn/PUwPGl2ACD2Sa5SRO9xzCCpskxxRhuUgSFGRVC1tqNwNke\niQ6HIw8a91wI5ijGko10FIB1/Onmt5aE+uCrSNIPLY9refWAeW3byldvnaOOnR/F\nabo1zgTpEkNImuFJ6/9iiujtE4txz3Plfc6g6G9n/YoHOtxPqJDcb+F3AoGBAOEl\noNGgVZQk9+0RIzbY12sg+FGZxQajavYFqmo1L52e8Iy17R5uHsxE5w71IsJG2PNK\noH0d4/eqedQJGFGtBUA5YXlcxlhvb7afxzDb3NAPF+00QAegLOFNRuaSDiPP37qR\n8nMAm1GZxhemq0hMqnAvPc5yA66YTnDVwdE7s1/nAoGAT8u9Xmaqifg+eGtYAp/g\nPRKCiS/mFQhjqUvTVvue6M85tDYgYrr8XE8fHzs+F0H7PBM9hv65QcQpYUR6FJI3\nveiUP4nwuPsswl7sI5sAoJoVNDmWOu0wio1luMjxscTk2W3IGkX2J8iH2kFNuUOe\nklkVXb9s+MkyMYxRuR8vnCECgYBfopojMRXo7aMaYhMxMv6eFM0l7ElSvouqoVF3\n98uYCnFnc8ebC2+tmP8EzX/MQkfZYDO3scCp7RH+zTY1S2dVloofAReHbR5o1onH\n6TxsbFzfdzhThOhLc4XQXu3+rEf+egwgaXuQN997IGLVPSuQp6B7VtbVjQCU0VeY\nxuE0tQKBgB0s+Ic3MkeQ60tWBCPTIBG7gPFkMk1NZ2rZyiRj18wg7RwlrxmI/B9C\nshBYSoB7IKYtYgs83e4e2yjetpNdjCj4WgI06RYxs86QG6xilmJ8/B8VEr80xFOK\nC9/y+nkKuIOGBJ/kHSXIPjviI3uLMbg4xsXJ75mHyQy2EFFTqFbj\n-----END RSA PRIVATE KEY-----"
      PUBLIC_KEY: "-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA3UqFbfl58DjvnWLVWTxE\n+THLXzzddeWD6bFnFdChnZv2sKo53XVv6DwMZonTKglltxgdUwXuPrvLnVuaV3i4\nqP8WscpQcieC2AP10ZYA1701tNFXFGlxDypaeZhqcXklet5aZ3uMvV/YhVl5SJrC\nY6k5r02X6lPE5/YgzwZjCOUJPGUQGRwb1W4vnguWBFCttriQSdDXy0q+wAdUYMB6\nEjV0ZCC8bej4P/iz8mtBwB9ULAr6IAIiVZq1O4jNPbDJribfL3ZbQGuZQV7JrAa+\n1Op3XEtr9Nu4kz71nPloFfMC4YnWSViXVR4koDgJkSlHlrpP+WcXT9uT25DcgNSb\nYQIDAQAB\n-----END PUBLIC KEY-----"
  db:
    container_name: classguardian_db
    image: postgres:13
    ports:
      - 5434:5432
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: classguardian
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres: ~